In [4]:
import numpy as np
from scipy.linalg import toeplitz
from SQR import SQR

In [5]:
N=500
P=1000
Corr=0.5**toeplitz(np.arange(0,P),np.arange(0,P))
beta=np.zeros((P,1))
beta[0]=3
beta[1]=1.5
beta[4]=2
beta[9]=1
beta[12]=1
beta[18]=0.5
beta[25]=-0.5
beta[30]=2.0
beta[45]=-1.2
beta[50]=-1
sigma1=1
sigma2=6
X=np.random.multivariate_normal(np.zeros(P), Corr, N)
Z=np.random.binomial(1, 0.8, size=(N,1))
Y=X@beta+(sigma1*Z+sigma2*(1-Z))*np.random.randn(N,1)

In [6]:
beta_estimator=SQR(Y,X,Q=0.5,C=0.5,s=1)

In [7]:
np.where(beta_estimator!=0)

(array([ 0,  1,  4,  9, 12, 18, 25, 30, 45, 50]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

In [8]:
beta_estimator[beta_estimator!=0]

array([ 3.01683639,  1.45905664,  1.85152287,  0.96187618,  0.97136128,
        0.38120449, -0.56259568,  1.89139287, -1.17272255, -1.05303806])